export const  SET_DEVICE_TREE = 'device/SET_DEVICE_TREE';
export const  SET_CURRENT_DEVICE_DATA = 'device/SET_CURRENT_DEVICE_DATA';
export const  SET_DASHBOARD_DEVICE_OPTION = 'device/SET_DASHBOARD_DEVICE_OPTION';
